name: mongodb
title: MongoDB
icon: mongodb

services:
- name: mongodb
  title: MongoDB
  service: mongodb

- name: mongoku
  title: Mongoku
  service: mongoku
  disabled: true
  links:
  - name: db
    service: mongodb
